// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA33balHc9sglwEYDvJXRKcGum1IqIEoYw',
    appId: '1:618267692066:web:d172a55b4da0bf2aed8e7b',
    messagingSenderId: '618267692066',
    projectId: 'agriflow-ai-27485',
    authDomain: 'agriflow-ai-27485.firebaseapp.com',
    storageBucket: 'agriflow-ai-27485.firebasestorage.app',
    measurementId: 'G-50VK76QRRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-RTJ3XxnFEVg1g03Wax0RbhluULylwSY',
    appId: '1:618267692066:android:196721ee792da767ed8e7b',
    messagingSenderId: '618267692066',
    projectId: 'agriflow-ai-27485',
    storageBucket: 'agriflow-ai-27485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9wr7a69ZtngLHiCTCUC3fQSpjoJAgPNg',
    appId: '1:618267692066:ios:a69e552f80b55c2ded8e7b',
    messagingSenderId: '618267692066',
    projectId: 'agriflow-ai-27485',
    storageBucket: 'agriflow-ai-27485.firebasestorage.app',
    iosBundleId: 'com.example.agriflowAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9wr7a69ZtngLHiCTCUC3fQSpjoJAgPNg',
    appId: '1:618267692066:ios:a69e552f80b55c2ded8e7b',
    messagingSenderId: '618267692066',
    projectId: 'agriflow-ai-27485',
    storageBucket: 'agriflow-ai-27485.firebasestorage.app',
    iosBundleId: 'com.example.agriflowAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA33balHc9sglwEYDvJXRKcGum1IqIEoYw',
    appId: '1:618267692066:web:20093b7c13afe349ed8e7b',
    messagingSenderId: '618267692066',
    projectId: 'agriflow-ai-27485',
    authDomain: 'agriflow-ai-27485.firebaseapp.com',
    storageBucket: 'agriflow-ai-27485.firebasestorage.app',
    measurementId: 'G-LQB6DDD8QL',
  );
}
