class CropData {
  static List<Map<String, dynamic>> crops = [
    {
      "name": "Paddy",
      "scientific": "Oryza sativa",
      "season": "Kharif",
      "duration": "120 Days",
      "water": "High",
      "climate": "Tropical",
      "temperature": "20° - 35°C",
      "soil": "Clay Loam",
      "yield": "4 - 6 Ton/ha",
      "sowing": "June - July",
      "harvesting": "Oct - Nov",
      "image": "assets/crops/paddy.jpg",
      "category": "Cereals",
      "overview":
          "Paddy is one of the most important staple cereal crops cultivated in India.",
      "cultivation": "Requires standing water and fertile soil.",
      "varieties": "IR64, MTU1010",
      "diseases": "Blast, Brown Spot",
      "market": "High demand in domestic markets.",
      "best": [
        "Maintain standing water",
        "Use certified seeds",
        "Apply balanced fertilizers",
      ],
    },
    {
      "name": "Wheat",
      "scientific": "Triticum aestivum",
      "season": "Rabi",
      "duration": "110 Days",
      "water": "Medium",
      "climate": "humid",
      "temperature": "15° - 25°C",
      "soil": "Loamy",
      "yield": "4 - 5 Ton/ha",
      "sowing": "Oct - Nov",
      "harvesting": "March",
      "image": "assets/crops/wheat.jpg",
      "category": "Cereals",
      "overview": "Wheat is one of the most cultivated cereal crops.",
      "cultivation": "Requires cool climate and proper irrigation.",
      "varieties": "HD2967, PBW343",
      "diseases": "Rust, Smut",
      "market": "Strong demand throughout India.",
      "best": [
        "Avoid waterlogging",
        "Use disease resistant seeds",
        "Maintain irrigation schedule",
      ],
    },
    {
      "name": "Maize",
      "scientific": "Zea mays",
      "season": "Kharif",
      "duration": "90 Days",
      "water": "Medium",
      "climate": "Tropical",
      "temperature": "20° - 32°C",
      "soil": "Sandy Loam",
      "yield": "5 - 7 Ton/ha",
      "sowing": "June",
      "harvesting": "Sept",
      "image": "assets/crops/maize.jpg",
      "category": "Cereals",
      "overview": "Maize is widely used for food and animal feed.",
      "cultivation": "Needs proper sunlight and irrigation.",
      "varieties": "HQPM1, DHM117",
      "diseases": "Leaf Blight, Rust",
      "market": "Good commercial value.",
      "best": [
        "Use hybrid seeds",
        "Maintain proper spacing",
        "Apply nitrogen fertilizers",
      ],
    },
    {
      "name": "Barley",
      "scientific": "Hordeum vulgare",
      "season": "Rabi",
      "duration": "100 Days",
      "water": "Low",
      "climate": "Tropical",
      "temperature": "12° - 25°C",
      "soil": "Loamy",
      "yield": "3 - 4 Ton/ha",
      "sowing": "Oct",
      "harvesting": "Feb",
      "image": "assets/crops/barley.jpg",
      "category": "Cereals",
      "overview": "Barley is used in beverages and animal feed.",
      "cultivation": "Requires cool climate and fertile soil.",
      "varieties": "RD2552, Jyoti",
      "diseases": "Leaf Rust, Smut",
      "market": "Moderate industrial demand.",
      "best": [
        "Avoid excess irrigation",
        "Use healthy seeds",
        "Apply organic manure",
      ],
    },
    {
      "name": "Millets",
      "scientific": "Pennisetum glaucum",
      "season": "Kharif",
      "duration": "85 Days",
      "water": "Low",
      "climate": "Tropical",
      "temperature": "25° - 35°C",
      "soil": "Sandy",
      "yield": "2 - 3 Ton/ha",
      "sowing": "June",
      "harvesting": "Sept",
      "image": "assets/crops/millets.jpg",
      "category": "Cereals",
      "overview": "Millets are nutritious drought resistant crops.",
      "cultivation": "Suitable for dry climate farming.",
      "varieties": "ICTP8203, HHB67",
      "diseases": "Downy Mildew, Smut",
      "market": "Increasing health market demand.",
      "best": [
        "Requires less water",
        "Suitable for dry areas",
        "Use organic farming methods",
      ],
    },
    {
      "name": "Sorghum",
      "scientific": "Sorghum bicolor",
      "season": "Kharif",
      "duration": "95 Days",
      "water": "Medium",
      "climate": "Tropical",
      "temperature": "22° - 33°C",
      "soil": "Black Soil",
      "yield": "3 - 5 Ton/ha",
      "sowing": "June",
      "harvesting": "Oct",
      "image": "assets/crops/sorghum.jpg",
      "category": "Cereals",
      "overview": "Sorghum is cultivated for food and fodder.",
      "cultivation": "Needs warm climate and moderate irrigation.",
      "varieties": "CSV15, CSH14",
      "diseases": "Rust, Anthracnose",
      "market": "Good livestock feed demand.",
      "best": [
        "Use hybrid varieties",
        "Timely irrigation is important",
        "Apply balanced fertilizers",
      ],
    },
    {
      "name": "Ragi",
      "scientific": "Eleusine coracana",
      "season": "Kharif",
      "duration": "100 Days",
      "water": "Medium",
      "climate": "Tropical",
      "temperature": "20° - 30°C",
      "soil": "Red Soil",
      "yield": "2 - 4 Ton/ha",
      "sowing": "June",
      "harvesting": "Oct",
      "image": "assets/crops/ragi.jpg",
      "category": "Cereals",
      "overview": "Ragi is rich in calcium and nutrients.",
      "cultivation": "Requires moderate rainfall and fertile soil.",
      "varieties": "GPU28, MR1",
      "diseases": "Blast Disease",
      "market": "Growing health food demand.",
      "best": [
        "Use disease resistant seeds",
        "Avoid water stagnation",
        "Maintain field hygiene",
      ],
    },
    {
      "name": "Oats",
      "scientific": "Avena sativa",
      "season": "Rabi",
      "duration": "110 Days",
      "water": "Medium",
      "climate": "Tropical",
      "temperature": "15° - 22°C",
      "soil": "Loamy",
      "yield": "3 - 5 Ton/ha",
      "sowing": "Nov",
      "harvesting": "March",
      "image": "assets/crops/oats.jpg",
      "category": "Cereals",
      "overview": "Oats are cultivated for food and fodder.",
      "cultivation": "Requires cool climate conditions.",
      "varieties": "Kent, OL9",
      "diseases": "Crown Rust",
      "market": "Used in breakfast cereals.",
      "best": [
        "Maintain irrigation schedule",
        "Use quality seeds",
        "Apply compost regularly",
      ],
    },
    {
      "name": "Bajra",
      "scientific": "Pennisetum glaucum",
      "season": "Kharif",
      "duration": "80 Days",
      "water": "Low",
      "climate": "Tropical",
      "temperature": "25° - 35°C",
      "soil": "Sandy",
      "yield": "2 - 3 Ton/ha",
      "sowing": "June",
      "harvesting": "Sept",
      "image": "assets/crops/bajra.jpg",
      "category": "Cereals",
      "overview": "Bajra is highly drought tolerant crop.",
      "cultivation": "Suitable for dryland agriculture.",
      "varieties": "HHB67, ICTP8203",
      "diseases": "Ergot, Smut",
      "market": "Healthy grain demand increasing.",
      "best": [
        "Requires less irrigation",
        "Suitable for arid regions",
        "Use drought resistant seeds",
      ],
    },
    {
      "name": "Foxtail Millet",
      "scientific": "Setaria italica",
      "season": "Kharif",
      "duration": "85 Days",
      "water": "Low",
      "climate": "Tropical",
      "temperature": "22° - 32°C",
      "soil": "Red Soil",
      "yield": "2 Ton/ha",
      "sowing": "June",
      "harvesting": "Sept",
      "image": "assets/crops/foxtail_millet.jpg",
      "category": "Cereals",
      "overview": "Foxtail millet is a nutritious millet crop.",
      "cultivation": "Requires less water and dry climate.",
      "varieties": "SiA3156, DHFt109",
      "diseases": "Leaf Spot",
      "market": "High health food demand.",
      "best": [
        "Needs low irrigation",
        "Suitable for dry farming",
        "Use organic fertilizers",
      ],
    },
    {
      "name": "Tomato",
      "scientific": "Solanum lycopersicum",
      "season": "Year Round",
      "duration": "90 - 120 Days",
      "water": "Medium",
      "climate": "Tropical",
      "temperature": "18° - 30°C",
      "soil": "Sandy Loam",
      "yield": "20 - 25 Ton/ha",
      "sowing": "June - July",
      "harvesting": "Sept - Nov",
      "image": "assets/crops/tomato.jpg",
      "category": "Vegetables",
      "overview": "Tomato is one of the most cultivated vegetable crops.",
      "cultivation": "Needs proper staking and irrigation management.",
      "varieties": "Arka Rakshak, Pusa Ruby",
      "diseases": "Leaf curl, Early blight",
      "market": "High demand in vegetable markets.",
      "best": [
        "Use drip irrigation",
        "Avoid excess watering",
        "Use organic compost",
        "Regular pest monitoring",
      ],
    },
    {
      "name": "Potato",
      "scientific": "Solanum tuberosum",
      "season": "Rabi",
      "duration": "90 - 120 Days",
      "water": "Medium",
      "climate": "Tropical",
      "temperature": "15° - 25°C",
      "soil": "Loamy Soil",
      "yield": "20 - 30 Ton/ha",
      "sowing": "Oct - Nov",
      "harvesting": "Jan - Feb",
      "image": "assets/crops/potato.jpg",
      "category": "Vegetables",
      "overview": "Potato is a widely cultivated underground vegetable crop.",
      "cultivation": "Requires cool climate and proper irrigation.",
      "varieties": "Kufri Jyoti, Kufri Bahar",
      "diseases": "Late blight, Early blight",
      "market": "High demand in food industry.",
      "best": [
        "Use certified seed tubers",
        "Avoid waterlogging",
        "Maintain proper spacing",
      ],
    },
    {
      "name": "Onion",
      "scientific": "Allium cepa",
      "season": "Rabi",
      "duration": "100 - 120 Days",
      "water": "Medium",
      "temperature": "18° - 28°C",
      "soil": "Loamy Soil",
      "yield": "15 - 20 Ton/ha",
      "sowing": "Nov",
      "harvesting": "March",
      "image": "assets/crops/onion.webp",
      "category": "Vegetables",
      "overview": "Onion is an important commercial vegetable crop.",
      "cultivation": "Needs fertile soil and regular irrigation.",
      "varieties": "N-53, Agrifound Dark Red",
      "diseases": "Purple blotch, Downy mildew",
      "market": "Strong market demand across India.",
      "best": [
        "Use drip irrigation",
        "Avoid excess moisture",
        "Store in dry conditions",
      ],
    },
    {
      "name": "Carrot",
      "scientific": "Daucus carota",
      "season": "Rabi",
      "duration": "90 Days",
      "water": "Medium",
      "temperature": "15° - 25°C",
      "soil": "Sandy Loam",
      "yield": "18 - 25 Ton/ha",
      "sowing": "Oct",
      "harvesting": "Jan",
      "image": "assets/crops/carrot.webp",
      "category": "Vegetables",
      "overview": "Carrot is rich in Vitamin A and antioxidants.",
      "cultivation": "Requires loose fertile soil for root development.",
      "varieties": "Pusa Rudhira, Nantes",
      "diseases": "Leaf blight, Root rot",
      "market": "Good urban market demand.",
      "best": [
        "Use loose soil",
        "Avoid stones in field",
        "Use organic manure",
      ],
    },
    {
      "name": "Cabbage",
      "scientific": "Brassica oleracea",
      "season": "Rabi",
      "duration": "90 - 120 Days",
      "water": "Medium",
      "temperature": "15° - 22°C",
      "soil": "Loamy",
      "yield": "25 - 35 Ton/ha",
      "sowing": "Oct",
      "harvesting": "Jan - Feb",
      "image": "assets/crops/cabbage.webp",
      "category": "Vegetables",
      "overview": "Cabbage is a cool season leafy vegetable crop.",
      "cultivation": "Requires fertile soil and cool climate.",
      "varieties": "Golden Acre, Pusa Drum Head",
      "diseases": "Black rot, Downy mildew",
      "market": "Good vegetable market demand.",
      "best": [
        "Maintain proper spacing",
        "Use organic compost",
        "Regular pest monitoring",
      ],
    },
    {
      "name": "Cauliflower",
      "scientific": "Brassica oleracea var. botrytis",
      "season": "Rabi",
      "duration": "90 - 110 Days",
      "water": "Medium",
      "temperature": "15° - 25°C",
      "soil": "Loamy",
      "yield": "20 - 30 Ton/ha",
      "sowing": "Sept - Oct",
      "harvesting": "Dec - Jan",
      "image": "assets/crops/cauliflower.jpg",
      "category": "Vegetables",
      "overview": "Cauliflower is a nutritious winter vegetable crop.",
      "cultivation": "Requires cool climate and fertile soil.",
      "varieties": "Pusa Snowball, Pant Gobhi",
      "diseases": "Black rot, Club root",
      "market": "High winter season demand.",
      "best": [
        "Maintain cool conditions",
        "Use quality seedlings",
        "Apply balanced fertilizers",
      ],
    },
    {
      "name": "Brinjal",
      "scientific": "Solanum melongena",
      "season": "Year Round",
      "duration": "120 Days",
      "water": "Medium",
      "temperature": "20° - 30°C",
      "soil": "Sandy Loam",
      "yield": "25 - 35 Ton/ha",
      "sowing": "June - July",
      "harvesting": "After 90 Days",
      "image": "assets/crops/brinjal.webp",
      "category": "Vegetables",
      "overview": "Brinjal is an important vegetable crop in India.",
      "cultivation": "Needs warm climate and regular irrigation.",
      "varieties": "Pusa Purple Long, Arka Nidhi",
      "diseases": "Fruit borer, Wilt",
      "market": "Steady vegetable market demand.",
      "best": [
        "Monitor fruit borers",
        "Use organic sprays",
        "Harvest regularly",
      ],
    },
    {
      "name": "Chilli",
      "scientific": "Capsicum annuum",
      "season": "Kharif",
      "duration": "150 Days",
      "water": "Medium",
      "temperature": "20° - 30°C",
      "soil": "Loamy Soil",
      "yield": "10 - 15 Ton/ha",
      "sowing": "June",
      "harvesting": "Nov - Dec",
      "image": "assets/crops/chilli.jpg",
      "category": "Vegetables",
      "overview": "Chilli is cultivated for spice and vegetable use.",
      "cultivation": "Requires warm climate and proper irrigation.",
      "varieties": "Byadagi, Guntur Sannam",
      "diseases": "Leaf curl, Anthracnose",
      "market": "High spice export demand.",
      "best": [
        "Use disease resistant varieties",
        "Avoid water stagnation",
        "Apply micronutrients",
      ],
    },
    {
      "name": "Lady Finger",
      "scientific": "Abelmoschus esculentus",
      "season": "Kharif",
      "duration": "60 - 90 Days",
      "water": "Medium",
      "temperature": "22° - 35°C",
      "soil": "Loamy Soil",
      "yield": "10 - 15 Ton/ha",
      "sowing": "June - July",
      "harvesting": "After 50 Days",
      "image": "assets/crops/ladyfinger.jpg",
      "category": "Vegetables",
      "overview": "Lady finger is a fast-growing vegetable crop.",
      "cultivation": "Needs warm climate and fertile soil.",
      "varieties": "Arka Anamika, Parbhani Kranti",
      "diseases": "Yellow vein mosaic",
      "market": "Strong daily market demand.",
      "best": [
        "Harvest regularly",
        "Use drip irrigation",
        "Control pests naturally",
      ],
    },
    {
      "name": "Spinach",
      "scientific": "Spinacia oleracea",
      "season": "Winter",
      "duration": "45 Days",
      "water": "Medium",
      "temperature": "15° - 25°C",
      "soil": "Loamy Soil",
      "yield": "8 - 12 Ton/ha",
      "sowing": "Oct - Nov",
      "harvesting": "After 40 Days",
      "image": "assets/crops/spinach.jpg",
      "category": "Vegetables",
      "overview": "Spinach is a nutritious leafy vegetable crop.",
      "cultivation": "Requires cool climate and moist soil.",
      "varieties": "All Green, Pusa Jyoti",
      "diseases": "Downy mildew",
      "market": "High urban market demand.",
      "best": [
        "Maintain soil moisture",
        "Use organic manure",
        "Harvest tender leaves",
      ],
    },
    {
      "name": "Beans",
      "scientific": "Phaseolus vulgaris",
      "season": "Kharif",
      "duration": "60 - 90 Days",
      "water": "Medium",
      "temperature": "18° - 28°C",
      "soil": "Loamy Soil",
      "yield": "8 - 10 Ton/ha",
      "sowing": "June - July",
      "harvesting": "After 50 Days",
      "image": "assets/crops/beans.jpg",
      "category": "Vegetables",
      "overview": "Beans are protein-rich vegetable crops.",
      "cultivation": "Needs proper support and irrigation.",
      "varieties": "Arka Komal, Contender",
      "diseases": "Rust, Mosaic virus",
      "market": "Good market demand.",
      "best": [
        "Provide staking support",
        "Avoid excess irrigation",
        "Use organic fertilizers",
      ],
    },
    {
      "name": "Peas",
      "scientific": "Pisum sativum",
      "season": "Rabi",
      "duration": "90 Days",
      "water": "Medium",
      "temperature": "13° - 25°C",
      "soil": "Loamy",
      "yield": "7 - 9 Ton/ha",
      "sowing": "Oct - Nov",
      "harvesting": "Jan - Feb",
      "image": "assets/crops/peas.jpg",
      "category": "Vegetables",
      "overview": "Peas are cool season legume vegetables.",
      "cultivation": "Requires cool climate and fertile soil.",
      "varieties": "Arkel, Bonneville",
      "diseases": "Powdery mildew",
      "market": "Good fresh vegetable demand.",
      "best": [
        "Use trellis support",
        "Maintain cool climate",
        "Apply compost regularly",
      ],
    },
    {
      "name": "Pumpkin",
      "scientific": "Cucurbita maxima",
      "season": "Kharif",
      "duration": "100 - 120 Days",
      "water": "Medium",
      "temperature": "20° - 32°C",
      "soil": "Sandy Loam",
      "yield": "20 - 25 Ton/ha",
      "sowing": "June",
      "harvesting": "Oct",
      "image": "assets/crops/pumpkin.jpg",
      "category": "Vegetables",
      "overview": "Pumpkin is a nutritious creeper vegetable crop.",
      "cultivation": "Needs warm climate and fertile soil.",
      "varieties": "Arka Chandan, Pusa Vishwas",
      "diseases": "Powdery mildew",
      "market": "Good seasonal market demand.",
      "best": [
        "Provide enough spacing",
        "Use organic compost",
        "Monitor fungal diseases",
      ],
    },
    {
      "name": "Cucumber",
      "scientific": "Cucumis sativus",
      "season": "Summer",
      "duration": "60 - 80 Days",
      "water": "High",
      "temperature": "20° - 30°C",
      "soil": "Sandy Loam",
      "yield": "10 - 15 Ton/ha",
      "sowing": "Feb - March",
      "harvesting": "After 50 Days",
      "image": "assets/crops/cucumber.webp",
      "category": "Vegetables",
      "overview": "Cucumber is a refreshing summer vegetable crop.",
      "cultivation": "Requires regular watering and warm climate.",
      "varieties": "Poinsett, Japanese Long Green",
      "diseases": "Downy mildew",
      "market": "Good summer market demand.",
      "best": [
        "Maintain soil moisture",
        "Use trellis system",
        "Harvest tender fruits",
      ],
    },
    {
      "name": "Radish",
      "scientific": "Raphanus sativus",
      "season": "Winter",
      "duration": "45 - 60 Days",
      "water": "Medium",
      "temperature": "10° - 25°C",
      "soil": "Sandy Loam",
      "yield": "10 - 15 Ton/ha",
      "sowing": "Oct - Nov",
      "harvesting": "After 45 Days",
      "image": "assets/crops/radish.jpg",
      "category": "Vegetables",
      "overview": "Radish is a fast-growing root vegetable crop.",
      "cultivation": "Requires loose fertile soil.",
      "varieties": "Pusa Chetki, Japanese White",
      "diseases": "White rust",
      "market": "Good winter vegetable demand.",
      "best": [
        "Use loose soil",
        "Avoid overcrowding",
        "Harvest at proper size",
      ],
    },
    {
      "name": "Mango",
      "scientific": "Mangifera indica",
      "season": "Summer",
      "duration": "4 - 5 Years",
      "water": "Medium",
      "temperature": "24° - 35°C",
      "soil": "Loamy Soil",
      "yield": "10 - 15 Ton/ha",
      "sowing": "July",
      "harvesting": "April - June",
      "image": "assets/crops/mango.jpg",
      "category": "Fruits",
      "overview": "Mango is known as the king of fruits.",
      "cultivation": "Requires warm climate and well-drained soil.",
      "varieties": "Alphonso, Banganapalli",
      "diseases": "Powdery mildew, Anthracnose",
      "market": "Very high domestic and export demand.",
      "best": [
        "Use grafted plants",
        "Avoid water stagnation",
        "Prune regularly",
      ],
    },
    {
      "name": "Banana",
      "scientific": "Musa",
      "season": "Year Round",
      "duration": "12 Months",
      "water": "High",
      "temperature": "25° - 35°C",
      "soil": "Loamy Soil",
      "yield": "30 - 40 Ton/ha",
      "sowing": "Year Round",
      "harvesting": "After 12 Months",
      "image": "assets/crops/banana.jpg",
      "category": "Fruits",
      "overview": "Banana is one of the most consumed fruits worldwide.",
      "cultivation": "Needs fertile soil and regular irrigation.",
      "varieties": "Grand Naine, Robusta",
      "diseases": "Panama wilt, Sigatoka",
      "market": "Strong year-round demand.",
      "best": [
        "Maintain proper irrigation",
        "Use tissue culture plants",
        "Apply organic manure",
      ],
    },
    {
      "name": "Apple",
      "scientific": "Malus domestica",
      "season": "Winter",
      "duration": "4 - 5 Years",
      "water": "Medium",
      "temperature": "10° - 24°C",
      "soil": "Loamy Soil",
      "yield": "15 - 20 Ton/ha",
      "sowing": "Dec",
      "harvesting": "Aug - Sept",
      "image": "assets/crops/apple.jpg",
      "category": "Fruits",
      "overview": "Apple is cultivated mainly in cold climate regions.",
      "cultivation": "Requires cool climate and fertile soil.",
      "varieties": "Red Delicious, Fuji",
      "diseases": "Apple scab, Fire blight",
      "market": "High market demand in urban areas.",
      "best": [
        "Use grafted saplings",
        "Prune regularly",
        "Maintain cold climate conditions",
      ],
    },
    {
      "name": "Orange",
      "scientific": "Citrus sinensis",
      "season": "Winter",
      "duration": "3 - 4 Years",
      "water": "Medium",
      "temperature": "20° - 30°C",
      "soil": "Sandy Loam",
      "yield": "12 - 18 Ton/ha",
      "sowing": "July",
      "harvesting": "Nov - Jan",
      "image": "assets/crops/orange.webp",
      "category": "Fruits",
      "overview": "Orange is a vitamin C rich citrus fruit crop.",
      "cultivation": "Needs warm climate and proper irrigation.",
      "varieties": "Nagpur Orange, Valencia",
      "diseases": "Citrus canker, Greening disease",
      "market": "Strong juice industry demand.",
      "best": [
        "Use disease free saplings",
        "Apply micronutrients",
        "Avoid waterlogging",
      ],
    },
    {
      "name": "Papaya",
      "scientific": "Carica papaya",
      "season": "Year Round",
      "duration": "9 - 12 Months",
      "water": "Medium",
      "temperature": "22° - 35°C",
      "soil": "Loamy Soil",
      "yield": "25 - 35 Ton/ha",
      "sowing": "June",
      "harvesting": "After 9 Months",
      "image": "assets/crops/papaya.jpg",
      "category": "Fruits",
      "overview": "Papaya is rich in vitamins and digestive enzymes.",
      "cultivation": "Requires warm climate and proper drainage.",
      "varieties": "Red Lady, Pusa Nanha",
      "diseases": "Papaya ring spot virus",
      "market": "Good health market demand.",
      "best": [
        "Avoid water stagnation",
        "Use healthy seedlings",
        "Monitor viral diseases",
      ],
    },
    {
      "name": "Watermelon",
      "scientific": "Citrullus lanatus",
      "season": "Summer",
      "duration": "80 - 100 Days",
      "water": "Medium",
      "temperature": "24° - 32°C",
      "soil": "Sandy Loam",
      "yield": "20 - 30 Ton/ha",
      "sowing": "Jan - Feb",
      "harvesting": "April - May",
      "image": "assets/crops/watermelon.webp",
      "category": "Fruits",
      "overview": "Watermelon is a refreshing summer fruit crop.",
      "cultivation": "Needs warm climate and sandy soil.",
      "varieties": "Sugar Baby, Arka Jyoti",
      "diseases": "Downy mildew, Wilt",
      "market": "Excellent summer demand.",
      "best": [
        "Use drip irrigation",
        "Maintain spacing",
        "Harvest mature fruits",
      ],
    },
    {
      "name": "Pineapple",
      "scientific": "Ananas comosus",
      "season": "Tropical",
      "duration": "18 Months",
      "water": "Medium",
      "temperature": "22° - 32°C",
      "soil": "Loamy Soil",
      "yield": "20 - 25 Ton/ha",
      "sowing": "June",
      "harvesting": "After 18 Months",
      "image": "assets/crops/pineapple.webp",
      "category": "Fruits",
      "overview": "Pineapple is a tropical fruit crop.",
      "cultivation": "Requires humid climate and fertile soil.",
      "varieties": "Kew, Queen",
      "diseases": "Heart rot",
      "market": "Good processing industry demand.",
      "best": [
        "Use healthy suckers",
        "Maintain moisture",
        "Apply organic manure",
      ],
    },
    {
      "name": "Grapes",
      "scientific": "Vitis vinifera",
      "season": "Winter",
      "duration": "3 Years",
      "water": "Medium",
      "temperature": "15° - 35°C",
      "soil": "Sandy Loam",
      "yield": "20 - 25 Ton/ha",
      "sowing": "Jan",
      "harvesting": "March - April",
      "image": "assets/crops/grapes.jpg",
      "category": "Fruits",
      "overview": "Grapes are cultivated for fresh fruit and wine production.",
      "cultivation": "Needs trellis support and pruning.",
      "varieties": "Thompson Seedless, Sharad Seedless",
      "diseases": "Powdery mildew",
      "market": "Excellent export demand.",
      "best": [
        "Regular pruning is important",
        "Use drip irrigation",
        "Provide trellis support",
      ],
    },
    {
      "name": "Guava",
      "scientific": "Psidium guajava",
      "season": "Year Round",
      "duration": "3 Years",
      "water": "Medium",
      "temperature": "20° - 30°C",
      "soil": "Loamy Soil",
      "yield": "15 - 20 Ton/ha",
      "sowing": "July",
      "harvesting": "After 3 Years",
      "image": "assets/crops/guava.jpg",
      "category": "Fruits",
      "overview": "Guava is rich in vitamin C and fiber.",
      "cultivation": "Requires warm climate and moderate irrigation.",
      "varieties": "Allahabad Safeda, Lucknow 49",
      "diseases": "Wilt, Anthracnose",
      "market": "Strong local market demand.",
      "best": [
        "Prune regularly",
        "Use organic manure",
        "Maintain proper spacing",
      ],
    },
    {
      "name": "Pomegranate",
      "scientific": "Punica granatum",
      "season": "Year Round",
      "duration": "3 Years",
      "water": "Low",
      "temperature": "18° - 35°C",
      "soil": "Sandy Loam",
      "yield": "10 - 15 Ton/ha",
      "sowing": "June",
      "harvesting": "Sept - Dec",
      "image": "assets/crops/pomegranate.jpg",
      "category": "Fruits",
      "overview": "Pomegranate is a high-value fruit crop.",
      "cultivation": "Needs dry climate and proper pruning.",
      "varieties": "Bhagwa, Ganesh",
      "diseases": "Bacterial blight",
      "market": "Excellent export demand.",
      "best": [
        "Avoid excess irrigation",
        "Use disease free plants",
        "Maintain orchard hygiene",
      ],
    },
    {
      "name": "Sapota",
      "scientific": "Manilkara zapota",
      "season": "Year Round",
      "duration": "4 Years",
      "water": "Medium",
      "temperature": "22° - 35°C",
      "soil": "Loamy Soil",
      "yield": "12 - 15 Ton/ha",
      "sowing": "July",
      "harvesting": "After 4 Years",
      "image": "assets/crops/sapota.webp",
      "category": "Fruits",
      "overview": "Sapota is a sweet tropical fruit crop.",
      "cultivation": "Requires warm climate and fertile soil.",
      "varieties": "Kalipatti, Cricket Ball",
      "diseases": "Leaf spot",
      "market": "Good local demand.",
      "best": [
        "Use organic compost",
        "Maintain proper irrigation",
        "Regular pruning is important",
      ],
    },
    {
      "name": "Lemon",
      "scientific": "Citrus limon",
      "season": "Year Round",
      "duration": "3 Years",
      "water": "Medium",
      "temperature": "20° - 30°C",
      "soil": "Sandy Loam",
      "yield": "10 - 12 Ton/ha",
      "sowing": "June - July",
      "harvesting": "After 3 Years",
      "image": "assets/crops/lemon.jpg",
      "category": "Fruits",
      "overview": "Lemon is a citrus fruit widely used in food industry.",
      "cultivation": "Needs proper irrigation and sunny climate.",
      "varieties": "Assam Lemon, Eureka",
      "diseases": "Citrus canker",
      "market": "Strong year-round demand.",
      "best": [
        "Avoid waterlogging",
        "Apply micronutrients",
        "Use healthy saplings",
      ],
    },
    {
      "name": "Jackfruit",
      "scientific": "Artocarpus heterophyllus",
      "season": "Summer",
      "duration": "5 Years",
      "water": "Medium",
      "temperature": "24° - 35°C",
      "soil": "Loamy Soil",
      "yield": "15 - 20 Ton/ha",
      "sowing": "June",
      "harvesting": "March - June",
      "image": "assets/crops/jackfruit.jpg",
      "category": "Fruits",
      "overview": "Jackfruit is a large tropical fruit crop.",
      "cultivation": "Requires humid climate and fertile soil.",
      "varieties": "Singapore Jack, Gulabi",
      "diseases": "Fruit rot",
      "market": "Good local and processing demand.",
      "best": [
        "Maintain tree spacing",
        "Use organic manure",
        "Monitor fungal diseases",
      ],
    },
    {
      "name": "Muskmelon",
      "scientific": "Cucumis melo",
      "season": "Summer",
      "duration": "80 - 90 Days",
      "water": "Medium",
      "temperature": "22° - 35°C",
      "soil": "Sandy Loam",
      "yield": "15 - 20 Ton/ha",
      "sowing": "Jan - Feb",
      "harvesting": "April - May",
      "image": "assets/crops/muskmelon.png",
      "category": "Fruits",
      "overview": "Muskmelon is a sweet summer fruit crop.",
      "cultivation": "Requires warm climate and fertile soil.",
      "varieties": "Hara Madhu, Punjab Sunehri",
      "diseases": "Powdery mildew",
      "market": "High summer demand.",
      "best": [
        "Maintain soil moisture",
        "Use organic compost",
        "Harvest ripe fruits",
      ],
    },
    {
      "name": "Green Gram",
      "scientific": "Vigna radiata",
      "season": "Kharif",
      "duration": "60 - 70 Days",
      "water": "Low",
      "temperature": "25° - 35°C",
      "soil": "Loamy Soil",
      "yield": "0.8 - 1 Ton/ha",
      "sowing": "June - July",
      "harvesting": "Sept",
      "image": "assets/crops/green_gram.jpg",
      "category": "Pulses",
      "overview":
          "Green gram is a protein-rich pulse crop widely cultivated in India.",
      "cultivation": "Requires warm climate and well-drained soil.",
      "varieties": "Pusa Vishal, SML668",
      "diseases": "Yellow mosaic virus",
      "market": "Good pulse market demand.",
      "best": [
        "Use certified seeds",
        "Avoid waterlogging",
        "Apply organic manure",
      ],
    },
    {
      "name": "Black Gram",
      "scientific": "Vigna mungo",
      "season": "Kharif",
      "duration": "80 - 90 Days",
      "water": "Low",
      "temperature": "25° - 35°C",
      "soil": "Clay Loam",
      "yield": "0.8 - 1.2 Ton/ha",
      "sowing": "June",
      "harvesting": "Sept - Oct",
      "image": "assets/crops/black_gram.webp",
      "category": "Pulses",
      "overview": "Black gram is an important pulse crop rich in protein.",
      "cultivation": "Requires warm climate and moderate rainfall.",
      "varieties": "PU31, LBG752",
      "diseases": "Leaf spot, Yellow mosaic",
      "market": "Strong market demand.",
      "best": [
        "Use disease resistant varieties",
        "Maintain field hygiene",
        "Use balanced fertilizers",
      ],
    },
    {
      "name": "Red Gram",
      "scientific": "Cajanus cajan",
      "season": "Kharif",
      "duration": "150 - 180 Days",
      "water": "Medium",
      "temperature": "20° - 35°C",
      "soil": "Red Soil",
      "yield": "1.5 - 2 Ton/ha",
      "sowing": "June - July",
      "harvesting": "Jan",
      "image": "assets/crops/red_gram.webp",
      "category": "Pulses",
      "overview": "Red gram is a major pulse crop cultivated widely in India.",
      "cultivation": "Needs warm climate and fertile soil.",
      "varieties": "ICPL87119, Asha",
      "diseases": "Wilt, Sterility mosaic",
      "market": "Very high demand.",
      "best": [
        "Avoid water stagnation",
        "Use certified seeds",
        "Monitor wilt disease",
      ],
    },
    {
      "name": "Bengal Gram",
      "scientific": "Cicer arietinum",
      "season": "Rabi",
      "duration": "100 - 120 Days",
      "water": "Low",
      "temperature": "18° - 30°C",
      "soil": "Black Soil",
      "yield": "1.5 - 2 Ton/ha",
      "sowing": "Oct - Nov",
      "harvesting": "Feb - March",
      "image": "assets/crops/bengal_gram.jpg",
      "category": "Pulses",
      "overview": "Bengal gram is one of the major pulse crops in India.",
      "cultivation": "Requires cool climate and less irrigation.",
      "varieties": "JG11, Pusa372",
      "diseases": "Wilt, Root rot",
      "market": "Excellent domestic demand.",
      "best": [
        "Use disease resistant seeds",
        "Avoid excess irrigation",
        "Apply organic compost",
      ],
    },
    {
      "name": "Horse Gram",
      "scientific": "Macrotyloma uniflorum",
      "season": "Kharif",
      "duration": "90 Days",
      "water": "Low",
      "temperature": "20° - 30°C",
      "soil": "Red Soil",
      "yield": "0.8 - 1 Ton/ha",
      "sowing": "June",
      "harvesting": "Sept",
      "image": "assets/crops/horse_gram.jpg",
      "category": "Pulses",
      "overview": "Horse gram is a drought resistant pulse crop.",
      "cultivation": "Suitable for dryland farming.",
      "varieties": "PHG9, AK21",
      "diseases": "Leaf spot",
      "market": "Good local market demand.",
      "best": [
        "Requires less irrigation",
        "Suitable for dry regions",
        "Use organic farming",
      ],
    },
    {
      "name": "Cowpea",
      "scientific": "Vigna unguiculata",
      "season": "Kharif",
      "duration": "70 - 90 Days",
      "water": "Medium",
      "temperature": "20° - 35°C",
      "soil": "Loamy Soil",
      "yield": "1 - 1.5 Ton/ha",
      "sowing": "June - July",
      "harvesting": "Sept",
      "image": "assets/crops/cowpea.webp",
      "category": "Pulses",
      "overview": "Cowpea is cultivated for pulse and fodder purposes.",
      "cultivation": "Needs warm climate and proper irrigation.",
      "varieties": "Pusa Komal, Arka Garima",
      "diseases": "Anthracnose",
      "market": "Good demand in local markets.",
      "best": [
        "Use quality seeds",
        "Maintain proper spacing",
        "Apply organic manure",
      ],
    },
    {
      "name": "Lentil",
      "scientific": "Lens culinaris",
      "season": "Rabi",
      "duration": "100 - 110 Days",
      "water": "Low",
      "temperature": "18° - 25°C",
      "soil": "Loamy Soil",
      "yield": "1 - 1.5 Ton/ha",
      "sowing": "Oct - Nov",
      "harvesting": "Feb",
      "image": "assets/crops/lentil.jpg",
      "category": "Pulses",
      "overview": "Lentil is an important winter pulse crop.",
      "cultivation": "Requires cool climate and fertile soil.",
      "varieties": "PL406, KLS218",
      "diseases": "Rust, Wilt",
      "market": "Strong pulse demand.",
      "best": [
        "Avoid excess moisture",
        "Use healthy seeds",
        "Apply balanced fertilizers",
      ],
    },
    {
      "name": "Peas ",
      "scientific": "Pisum sativum",
      "season": "Rabi",
      "duration": "90 - 100 Days",
      "water": "Medium",
      "temperature": "13° - 25°C",
      "soil": "Loamy Soil",
      "yield": "1.5 - 2 Ton/ha",
      "sowing": "Oct - Nov",
      "harvesting": "Jan - Feb",
      "image": "assets/crops/peas.jpg",
      "category": "Pulses",
      "overview": "Peas pulse is cultivated as an important winter pulse crop.",
      "cultivation": "Requires cool climate and fertile soil.",
      "varieties": "Arkel, Bonneville",
      "diseases": "Powdery mildew",
      "market": "Good seasonal demand.",
      "best": [
        "Provide proper irrigation",
        "Use quality seeds",
        "Maintain cool climate",
      ],
    },
    {
      "name": "Soybean",
      "scientific": "Glycine max",
      "season": "Kharif",
      "duration": "90 - 110 Days",
      "water": "Medium",
      "temperature": "20° - 30°C",
      "soil": "Black Soil",
      "yield": "2 - 3 Ton/ha",
      "sowing": "June",
      "harvesting": "Oct",
      "image": "assets/crops/soybean.jpg",
      "category": "Pulses",
      "overview":
          "Soybean is an important oilseed and protein-rich pulse crop.",
      "cultivation": "Requires fertile soil and warm climate.",
      "varieties": "JS335, NRC37",
      "diseases": "Rust, Yellow mosaic",
      "market": "Excellent industrial demand.",
      "best": [
        "Use certified seeds",
        "Apply balanced fertilizers",
        "Monitor pest attacks",
      ],
    },
    {
      "name": "Groundnut",
      "scientific": "Arachis hypogaea",
      "season": "Kharif",
      "duration": "110 - 120 Days",
      "water": "Medium",
      "temperature": "20° - 30°C",
      "soil": "Sandy Loam",
      "yield": "2 - 3 Ton/ha",
      "sowing": "June - July",
      "harvesting": "Oct - Nov",
      "image": "assets/crops/groundnut.jpg",
      "category": "Oil Seeds",
      "overview":
          "Groundnut is an important oilseed crop cultivated widely in India.",
      "cultivation": "Requires warm climate and well-drained soil.",
      "varieties": "TMV2, JL24",
      "diseases": "Leaf spot, Rust",
      "market": "High edible oil demand.",
      "best": [
        "Use certified seeds",
        "Avoid waterlogging",
        "Apply gypsum during flowering",
      ],
    },
    {
      "name": "Sunflower",
      "scientific": "Helianthus annuus",
      "season": "Kharif",
      "duration": "90 - 110 Days",
      "water": "Medium",
      "temperature": "18° - 30°C",
      "soil": "Well Drained Soil",
      "yield": "2 - 2.5 Ton/ha",
      "sowing": "June",
      "harvesting": "Sept - Oct",
      "image": "assets/crops/sunflower.jpg",
      "category": "Oil Seeds",
      "overview": "Sunflower is cultivated mainly for edible oil production.",
      "cultivation": "Needs proper sunlight and moderate irrigation.",
      "varieties": "KBSH44, Morden",
      "diseases": "Downy mildew, Rust",
      "market": "Strong cooking oil demand.",
      "best": [
        "Maintain proper spacing",
        "Use balanced fertilizers",
        "Monitor fungal diseases",
      ],
    },
    {
      "name": "Sesame",
      "scientific": "Sesamum indicum",
      "season": "Kharif",
      "duration": "80 - 100 Days",
      "water": "Low",
      "temperature": "25° - 35°C",
      "soil": "Sandy Loam",
      "yield": "0.8 - 1 Ton/ha",
      "sowing": "June - July",
      "harvesting": "Sept",
      "image": "assets/crops/sesame.jpg",
      "category": "Oil Seeds",
      "overview":
          "Sesame is one of the oldest oilseed crops cultivated in India.",
      "cultivation": "Requires dry climate and fertile soil.",
      "varieties": "TMV7, VRI1",
      "diseases": "Leaf spot, Root rot",
      "market": "Good export demand.",
      "best": [
        "Avoid excess irrigation",
        "Use healthy seeds",
        "Maintain field drainage",
      ],
    },
    {
      "name": "Mustard",
      "scientific": "Brassica juncea",
      "season": "Rabi",
      "duration": "110 - 130 Days",
      "water": "Low",
      "temperature": "10° - 25°C",
      "soil": "Loamy Soil",
      "yield": "1.5 - 2 Ton/ha",
      "sowing": "Oct - Nov",
      "harvesting": "Feb - March",
      "image": "assets/crops/mustard.jpg",
      "category": "Oil Seeds",
      "overview":
          "Mustard is a major oilseed crop cultivated during winter season.",
      "cultivation": "Requires cool climate and less irrigation.",
      "varieties": "Pusa Bold, Varuna",
      "diseases": "White rust, Alternaria blight",
      "market": "High edible oil demand.",
      "best": [
        "Use certified seeds",
        "Avoid water stagnation",
        "Apply sulfur fertilizers",
      ],
    },
    {
      "name": "Castor",
      "scientific": "Ricinus communis",
      "season": "Kharif",
      "duration": "150 - 180 Days",
      "water": "Medium",
      "temperature": "20° - 30°C",
      "soil": "Red Soil",
      "yield": "1.5 - 2 Ton/ha",
      "sowing": "June",
      "harvesting": "Dec - Jan",
      "image": "assets/crops/castor.jpg",
      "category": "Oil Seeds",
      "overview": "Castor is an important industrial oilseed crop.",
      "cultivation": "Requires warm climate and moderate irrigation.",
      "varieties": "GCH7, DCH177",
      "diseases": "Wilt, Leaf spot",
      "market": "Good industrial oil demand.",
      "best": [
        "Use hybrid varieties",
        "Avoid excess moisture",
        "Monitor wilt disease",
      ],
    },
    {
      "name": "Linseed",
      "scientific": "Linum usitatissimum",
      "season": "Rabi",
      "duration": "120 Days",
      "water": "Low",
      "temperature": "15° - 25°C",
      "soil": "Loamy Soil",
      "yield": "1 - 1.5 Ton/ha",
      "sowing": "Oct",
      "harvesting": "Feb",
      "image": "assets/crops/linseed.jpg",
      "category": "Oil Seeds",
      "overview": "Linseed is cultivated for oil and fiber purposes.",
      "cultivation": "Requires cool climate and fertile soil.",
      "varieties": "Neela, Sharda",
      "diseases": "Rust, Wilt",
      "market": "Moderate industrial demand.",
      "best": [
        "Maintain proper irrigation",
        "Use quality seeds",
        "Apply balanced nutrients",
      ],
    },
    {
      "name": "Soybean Oil",
      "scientific": "Glycine max",
      "season": "Kharif",
      "duration": "90 - 110 Days",
      "water": "Medium",
      "temperature": "20° - 30°C",
      "soil": "Black Soil",
      "yield": "2 - 3 Ton/ha",
      "sowing": "June",
      "harvesting": "Oct",
      "image": "assets/crops/soybean_oil.jpg",
      "category": "Oil Seeds",
      "overview": "Soybean is an important oilseed and protein-rich crop.",
      "cultivation": "Requires fertile soil and warm climate.",
      "varieties": "JS335, NRC37",
      "diseases": "Rust, Yellow mosaic",
      "market": "Excellent edible oil demand.",
      "best": [
        "Use certified seeds",
        "Monitor pest attacks",
        "Apply organic compost",
      ],
    },
    {
      "name": "Niger Seed",
      "scientific": "Guizotia abyssinica",
      "season": "Kharif",
      "duration": "90 - 100 Days",
      "water": "Low",
      "temperature": "20° - 30°C",
      "soil": "Red Soil",
      "yield": "0.5 - 1 Ton/ha",
      "sowing": "June - July",
      "harvesting": "Sept - Oct",
      "image": "assets/crops/niger_seed.jpg",
      "category": "Oil Seeds",
      "overview": "Niger seed is cultivated mainly for edible oil extraction.",
      "cultivation": "Suitable for dryland farming conditions.",
      "varieties": "IGP76, JNC6",
      "diseases": "Leaf spot",
      "market": "Good local oil demand.",
      "best": [
        "Requires less irrigation",
        "Suitable for dry areas",
        "Use quality seeds",
      ],
    },
    {
      "name": "Safflower",
      "scientific": "Carthamus tinctorius",
      "season": "Rabi",
      "duration": "120 - 140 Days",
      "water": "Low",
      "temperature": "20° - 30°C",
      "soil": "Black Soil",
      "yield": "1 - 1.5 Ton/ha",
      "sowing": "Oct - Nov",
      "harvesting": "March",
      "image": "assets/crops/safflower.jpg",
      "category": "Oil Seeds",
      "overview": "Safflower is cultivated for edible oil and medicinal uses.",
      "cultivation": "Requires dry climate and fertile soil.",
      "varieties": "A1, PBNS12",
      "diseases": "Wilt, Alternaria blight",
      "market": "Moderate oil market demand.",
      "best": [
        "Avoid excess irrigation",
        "Use healthy seeds",
        "Apply balanced fertilizers",
      ],
    },
    {
      "name": "Coconut",
      "scientific": "Cocos nucifera",
      "season": "Tropical",
      "duration": "5 - 7 Years",
      "water": "High",
      "temperature": "25° - 35°C",
      "soil": "Sandy Loam",
      "yield": "80 - 100 Nuts/Tree",
      "sowing": "June - July",
      "harvesting": "Year Round",
      "image": "assets/crops/coconut.jpg",
      "category": "Oil Seeds",
      "overview": "Coconut is an important plantation and oilseed crop.",
      "cultivation": "Requires humid climate and regular irrigation.",
      "varieties": "West Coast Tall, Chowghat Orange Dwarf",
      "diseases": "Root wilt, Bud rot",
      "market": "Excellent edible oil and copra demand.",
      "best": [
        "Maintain soil moisture",
        "Apply organic manure",
        "Monitor root diseases",
      ],
    },
    {
      "name": "Cotton",
      "scientific": "Gossypium",
      "season": "Kharif",
      "duration": "160 - 180 Days",
      "water": "Medium",
      "temperature": "21° - 30°C",
      "soil": "Black Soil",
      "yield": "2 - 4 Ton/ha",
      "sowing": "June - July",
      "harvesting": "Nov - Jan",
      "image": "assets/crops/cotton.jpg",
      "category": "Cash Crops",
      "overview":
          "Cotton is one of the most important commercial fiber crops cultivated widely in India.",
      "cultivation": "Requires warm climate and fertile black soil.",
      "varieties": "Bt Cotton, MCU5",
      "diseases": "Bollworm, Wilt",
      "market": "Excellent textile industry demand.",
      "best": [
        "Use hybrid seeds",
        "Monitor pest attacks regularly",
        "Avoid excess irrigation",
      ],
    },
    {
      "name": "Sugarcane",
      "scientific": "Saccharum officinarum",
      "season": "Annual",
      "duration": "10 - 14 Months",
      "water": "High",
      "temperature": "20° - 35°C",
      "soil": "Loamy Soil",
      "yield": "60 - 100 Ton/ha",
      "sowing": "Jan - March",
      "harvesting": "Dec - Feb",
      "image": "assets/crops/sugarcane.jpg",
      "category": "Cash Crops",
      "overview": "Sugarcane is a major commercial crop for sugar production.",
      "cultivation": "Needs high irrigation and fertile soil.",
      "varieties": "Co86032, Co0238",
      "diseases": "Red rot, Wilt",
      "market": "Excellent industrial demand.",
      "best": [
        "Use healthy setts",
        "Proper drainage is essential",
        "Apply organic manure",
        "Frequent irrigation required",
      ],
    },
    {
      "name": "Coffee",
      "scientific": "Coffea arabica",
      "season": "Perennial",
      "duration": "3 - 4 Years",
      "water": "Medium",
      "temperature": "18° - 28°C",
      "soil": "Loamy Soil",
      "yield": "800 - 1000 Kg/ha",
      "sowing": "June - July",
      "harvesting": "Nov - Jan",
      "image": "assets/crops/coffee.jpg",
      "category": "Cash Crops",
      "overview":
          "Coffee is an important plantation crop grown in hilly regions.",
      "cultivation": "Requires shade, moderate rainfall and cool climate.",
      "varieties": "Arabica, Robusta",
      "diseases": "Coffee rust, Berry disease",
      "market": "Strong export demand.",
      "best": [
        "Maintain shade trees",
        "Use organic compost",
        "Monitor fungal diseases",
      ],
    },
    {
      "name": "Tea",
      "scientific": "Camellia sinensis",
      "season": "Perennial",
      "duration": "3 - 5 Years",
      "water": "High",
      "temperature": "18° - 30°C",
      "soil": "Acidic Soil",
      "yield": "2000 - 2500 Kg/ha",
      "sowing": "June",
      "harvesting": "Year Round",
      "image": "assets/crops/tea.webp",
      "category": "Cash Crops",
      "overview": "Tea is one of the major plantation crops in India.",
      "cultivation": "Requires humid climate and high rainfall.",
      "varieties": "Assam Tea, Darjeeling Tea",
      "diseases": "Blister blight",
      "market": "Very high domestic and export demand.",
      "best": [
        "Maintain soil acidity",
        "Regular pruning is essential",
        "Use organic manure",
      ],
    },
    {
      "name": "Rubber",
      "scientific": "Hevea brasiliensis",
      "season": "Tropical",
      "duration": "6 - 7 Years",
      "water": "High",
      "temperature": "25° - 35°C",
      "soil": "Laterite Soil",
      "yield": "1500 - 2000 Kg/ha",
      "sowing": "June - July",
      "harvesting": "After 6 Years",
      "image": "assets/crops/rubber.jpg",
      "category": "Cash Crops",
      "overview": "Rubber is an important industrial plantation crop.",
      "cultivation": "Requires humid tropical climate and regular rainfall.",
      "varieties": "RRII105, GT1",
      "diseases": "Leaf fall disease",
      "market": "Strong tire and industrial demand.",
      "best": [
        "Maintain plantation hygiene",
        "Use disease resistant clones",
        "Regular tapping management",
      ],
    },
    {
      "name": "Tobacco",
      "scientific": "Nicotiana tabacum",
      "season": "Rabi",
      "duration": "120 - 150 Days",
      "water": "Medium",
      "temperature": "20° - 30°C",
      "soil": "Sandy Loam",
      "yield": "1.5 - 2 Ton/ha",
      "sowing": "Oct - Nov",
      "harvesting": "Feb - March",
      "image": "assets/crops/tobacco.jpg",
      "category": "Cash Crops",
      "overview":
          "Tobacco is a commercial crop cultivated for leaf production.",
      "cultivation": "Requires warm climate and fertile soil.",
      "varieties": "FCV Tobacco, Burley",
      "diseases": "Mosaic virus, Black shank",
      "market": "Strong industrial demand.",
      "best": [
        "Maintain proper curing process",
        "Use certified seedlings",
        "Avoid excess irrigation",
      ],
    },
    {
      "name": "Cocoa",
      "scientific": "Theobroma cacao",
      "season": "Tropical",
      "duration": "3 - 5 Years",
      "water": "High",
      "temperature": "21° - 32°C",
      "soil": "Loamy Soil",
      "yield": "800 - 1200 Kg/ha",
      "sowing": "June",
      "harvesting": "Year Round",
      "image": "assets/crops/cocoa.webp",
      "category": "Cash Crops",
      "overview": "Cocoa is cultivated mainly for chocolate production.",
      "cultivation": "Requires humid climate and shade conditions.",
      "varieties": "Forastero, Criollo",
      "diseases": "Black pod disease",
      "market": "Excellent chocolate industry demand.",
      "best": [
        "Maintain shade management",
        "Use organic fertilizers",
        "Monitor fungal diseases",
      ],
    },
    {
      "name": "Jute",
      "scientific": "Corchorus olitorius",
      "season": "Kharif",
      "duration": "120 Days",
      "water": "High",
      "temperature": "24° - 35°C",
      "soil": "Alluvial Soil",
      "yield": "2 - 3 Ton/ha",
      "sowing": "March - April",
      "harvesting": "July - Aug",
      "image": "assets/crops/jute.jpg",
      "category": "Cash Crops",
      "overview": "Jute is an important fiber cash crop.",
      "cultivation": "Requires warm humid climate and fertile soil.",
      "varieties": "JRO524, JRC321",
      "diseases": "Stem rot",
      "market": "Good eco-friendly fiber demand.",
      "best": [
        "Maintain soil moisture",
        "Use quality seeds",
        "Proper retting is important",
      ],
    },
    {
      "name": "Arecanut",
      "scientific": "Areca catechu",
      "season": "Tropical",
      "duration": "5 - 7 Years",
      "water": "High",
      "temperature": "20° - 35°C",
      "soil": "Red Loamy Soil",
      "yield": "1 - 2 Ton/ha",
      "sowing": "June - July",
      "harvesting": "Year Round",
      "image": "assets/crops/arecanut.jpg",
      "category": "Cash Crops",
      "overview": "Arecanut is an important plantation cash crop.",
      "cultivation": "Requires humid climate and regular irrigation.",
      "varieties": "Mangala, Sumangala",
      "diseases": "Fruit rot, Yellow leaf disease",
      "market": "Very strong market demand in South India.",
      "best": [
        "Maintain irrigation regularly",
        "Use organic manure",
        "Monitor fungal diseases",
      ],
    },
    {
      "name": "Cardamom",
      "scientific": "Elettaria cardamomum",
      "season": "Perennial",
      "duration": "3 - 4 Years",
      "water": "High",
      "temperature": "15° - 30°C",
      "soil": "Forest Loamy Soil",
      "yield": "200 - 300 Kg/ha",
      "sowing": "June",
      "harvesting": "Oct - Feb",
      "image": "assets/crops/cardamom.jpg",
      "category": "Cash Crops",
      "overview": "Cardamom is known as the queen of spices.",
      "cultivation": "Requires cool humid climate and shade.",
      "varieties": "Malabar, Mysore",
      "diseases": "Capsule rot",
      "market": "Excellent export spice demand.",
      "best": [
        "Maintain shade conditions",
        "Apply organic compost",
        "Use disease free seedlings",
      ],
    },
  ];
}
